services:
  backend:
    build: ./backend
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/app
      - ~/.ssh:/root/.ssh
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  
    working_dir: /usr/app  
  frontend:
    build: ./frontend
    platform: linux/amd64
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
        - NODE_ENV=development